services:
  redis:
    image: 'bitnami/redis:7.4'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
  redis-replica:
    image: 'bitnami/redis:7.4'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - ALLOW_EMPTY_PASSWORD=yes
  sentinel:
    image: 'bitnami/redis-sentinel:7.4'
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_SET=redis
    ports:
      - '26379:26379'
    depends_on:
      - redis
      - redis-replica
  vector:
    image: "timberio/vector:0.41.0-alpine"
    volumes:
      - "./vector.toml:/etc/vector/vector.toml:ro"
    depends_on:
      - redis
      - logs-exporter
  logs-exporter:
    build:
      context: ../
      dockerfile: Dockerfile
      target: prod
    env_file: .docker.env
    depends_on:
      - sentinel
